project:
  type: website
  output-dir: docs


website:
  google-analytics: "G-B9BQN0XN58"
  sidebar:
    style: "docked"
    search: true
    title: "Moïse Placier Porfolio"
    contents:
      - section: "curriculum vitae : english"
        contents:
          - href: Exp_pro_en.qmd
            text: "Professional experiences"
          - href: Educ_en.qmd
            text: "Education"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    

