---
title: "Education"
author: "Moïse Placier"
published_Date: 10/04/2024
format:
  html

---

### [Berliner Hochschule für Technik](https://www.bht-berlin.de/) - (Berlin, Germany ) - Academic Exchange : [M.Sc. Data Science 2025](https://www.bht-berlin.de/m-ds)

Regression, Machine learning, Data Science workflow, Natural Language Processing, Data visualisation

#### Hochschule für Wirtschaft und Recht - (Berlin, Germany ) - mars 2025 - avr. 2025
  German language and literature


### [École Nationale Supérieure Agronomique de Toulouse](https://www.ensat.fr/fr/index.html) (ENSAT) - ( Toulouse, France ) 2022-2025

Graduate School accessible through a competitive entrance exam, offering a comprehensive Master's-level Engineering Degree with a focus on life sciences, agriculture, food sciences, environmental sciences, data science, project management, and production systems analysis.



### Preparatory Classes for Grandes Écoles - BCPST (Chaptal, Paris, France ) - 2020 à 2022

A highly selective two-year intensive program designed to prepare students for competitive entrance exams to France’s top engineering schools (Grandes Écoles). The BCPST track focuses on advanced studies in Biology, Chemistry, Physics, Earth Sciences, and Mathematics. This rigorous program emphasizes analytical thinking, problem-solving, and academic excellence.

### High School Diploma -Baccalauréat ( Évreux, France ) 2020

Scientific Baccalauréat with a focus on Life and Earth Sciences, graduated with high honors
